### ISSUE TITLE
An empty resultset returned from current 'test.bleve' index

### ISSUE THREAD

**Issue by mukil** [blevesearch/bleve-hosted#3]
After starting the service:

<pre>
michel@tschakko:~/go-home/src/github.com/blevesearch/bleve-hosted$ bleve-hosted 
2015/10/15 18:02:39 opening indexes
2015/10/15 18:02:39 registered index: test.bleve
2015/10/15 18:02:39 Listening on :8080
</pre>

The test query (mentioned at http://www.blevesearch.com/news/Site-Search/) returns zero results:

<pre>
michel@tschakko:~$ curl http://localhost:8080/api/test.bleve/_search -d '{"query":{"query":"bleve"}}'
curl: (52) Empty reply from server
</pre>

Any ideas?
Thanks  & Cheers!

**Comment by mschoch** [comment]
That is odd, I just tried it again in a clean go path and it seemed to still work as described:

```
$ mkdir /tmp/gopath
$ export GOPATH=/tmp/gopath
$ go get github.com/blevesearch/bleve-hosted
$ cd /tmp/gopath/src/github.com/blevesearch/bleve-hosted/
$ /tmp/gopath/bin/bleve-hosted
2015/10/16 11:27:23 opening indexes
2015/10/16 11:27:23 registered index: test.bleve
2015/10/16 11:27:23 Listening on :8080
```

Then in another console:

```
$ curl http://localhost:8080/api/test.bleve/_search -d '{"query":{"query":"bleve"}}'
{"request":{"query":{"query":"bleve","boost":1},"size":0,"from":0,"highlight":null,"fields":null,"facets":null,"explain":false},"hits":[],"total_hits":1,"max_score":0.1372287510279364,"took":314684,"facets":{}}
```

The message: `curl: (52) Empty reply from server` suggests something pretty severe is going on inside bleve-hosted.  Do any other messages show up from the process running bleve-hosted?  Is it possible some other dependency of bleve is out of data and not updated?

**Comment by mukil** [comment]
Hi, thanks for your guidance and sorry for my very late reply.

If i try things on another machine (A) (where go was never installed before) i get the same result like you describe. Doing the exact same steps back on another machine (B) where i experienced this issue originally, i still get the `curl: (52) Empty reply from server`. 

Also after setting up a fresh go download (`go version go1.5.1 linux/amd64`) there and introducing that into my PATH environment variable + starting with a clean GOPATH.

The only difference between the go setup on (A) and (B) is that on (B) i had it installed `go` via the ubuntu package manager (and thus once ran an old version before). Normally that _should_ be solved with the steps you described here!

Now, other than setting up a new go installation which runs bleve-hosted (as described in the steps here [above](https://github.com/blevesearch/bleve-hosted/issues/3#issuecomment-148746987)) i currently have no idea how i could get rid of the error on (B). 

Do you think we/i could try to track down the issue to a specific module through making the service implementation more verbose?

**Comment by mschoch** [comment]
I would add this line to main before the ListenAndServe call:

```
log.Printf("Go Runtime: %s", runtime.Version())
```

That will confirm which Go runtime the program was compiled with.

Second, the bleve/http package already has support for logging some information, but the logger output is discarded by default.  You can change that by adding the following line to bleve.go at the top of the init method:

```
bleveHttp.SetLog(log.New(os.Stderr, "bleve.http ", log.LstdFlags))
```

This will log the raw bytes of the request, and the parsed structure (if it's even making it that far).  Then if it gets past that point, you may need to add additional lines to this section:

https://github.com/blevesearch/bleve/blob/master/http/search.go#L33-L84

As we know it's not making it to the end of that function.

Hope this helps, please let me know what you find.

**Comment by mukil** [comment]
Ok, thanks for your help! Now this is all i got on server side: 

<pre>
michel@tschakko:~/go-path/bin$ ./bleve-hosted 
2015/12/15 17:00:02 opening indexes
2015/12/15 17:00:02 registered index: test.bleve
2015/12/15 17:00:02 Listening on :8080
2015/12/15 17:00:02 Go Runtime: go1.5.1
</pre>

And on client side still:

<pre>
mikel@tschakko:~$ curl http://localhost:8080/api/test.bleve/_search -d '{"query":{"query":"bleve"}}'
curl: (52) Empty reply from server
</pre>

**Comment by mschoch** [comment]
It it possible something else is listening to 8080 on that machine?  We're not seeing any indication on the server that a request was received.

Also, you can try using the -addr flag to specify an alternate bind address.

**Comment by mukil** [comment]
When i start the `bleve-hosted` service and then issue the search request via `curl` from "outside" (e.g. from my laptop), the issue disappears! I now get a nice reply of the bleve-hosted search service:

<pre>
michel@work:~$ curl http://my-bleve-hosted-machine:8080/api/test.bleve/_search -d '{"query":{"query":"bleve"}}'
{"request":{"query":{"query":"bleve","boost":1},"size":0,"from":0,"highlight":null,"fields":null,"facets":null,"explain":false},"hits":[],"total_hits":1,"max_score":0.1372287510279364,"took":479766,"facets":{}}
</pre>

I guess that this problem is related to the system wide "Proxy Settings" on that machine and that `curl` can not resolve the request to "localhost" and thus gives that response `curl: (52) Empty reply from server`! 

Holy moly, thanks a lot for your patience and support!
